name: Create VS Code Extension Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to use Node.js 20

    - name: Set up Node.js
      uses: actions/setup-node@v4  # Updated to use Node.js 20
      with:
        node-version: '22.6.0'

    - name: Install vsce
      run: npm install -g vsce

    - name: Install dependencies
      run: npm install

    - name: Package the extension
      run: |
        vsce package -o ./ai-context-manager.vsix
        ls -al  # List all files to confirm the .vsix file name and location

    - name: Create and Upload Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./ai-context-manager.vsix
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
