name: Create VS Code Extension Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.6.0'

    - name: Install vsce
      run: npm install -g vsce

    - name: Install dependencies
      run: npm install

    - name: Package the extension
      run: vsce package

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}  # Uses the tag that triggered the workflow
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true

    - name: Upload VSIX to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: './ai-context-manager-*.vsix'  # Path to the VSIX file
        asset_name: 'ai-context-manager.vsix'
        asset_content_type: 'application/octet-stream'