name: Run Tests

on:
  pull_request:
    branches:
      - main  # Specify the branch you want to trigger the action on PRs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.6.0'  # Updated to the latest Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test
